#!/usr/bin/env python3
"""
Integration tests for github template.

Auto-generated by TemplateTestGenerator.
Tests actual deployment and container functionality.
"""

import sys
import time
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

from mcp_template import MCPDeployer
from tests.utils.mcp_test_utils import build_and_run_template


@pytest.mark.integration
@pytest.mark.docker
class TestGithubIntegration:
    """Integration tests for github template deployment."""

    @pytest.fixture
    def deployer(self):
        """MCPDeployer fixture."""
        return MCPDeployer()

    def test_template_deployment(self, deployer):
        """Test successful template deployment."""
        # Skip if template not available
        if "github" not in deployer.templates:
            pytest.skip("github template not available")

        # Deploy template
        success = deployer.deploy("github")
        assert success, "Template deployment should succeed"

        # Wait for container to start
        time.sleep(3)

        # Verify deployment
        deployments = deployer.deployment_manager.list_deployments()
        template_deployments = [d for d in deployments if d["template"] == "github"]
        assert len(template_deployments) > 0, "Deployed template should appear in list"

        # Cleanup
        for deployment in template_deployments:
            deployer.deployment_manager.delete_deployment(deployment["name"])

    def test_container_health(self):
        """Test container starts and runs healthily."""
        config = {
            "default_owner": "",
            "default_repo": "",
            "api_base_url": "https://api.github.com",
            "max_search_results": 30,
            "enable_webhook_events": False,
            "rate_limit_requests": 5000,
        }

        with build_and_run_template("github", config) as container:
            # Container should start successfully
            assert container.container_id, "Container should have valid ID"

            # Check container logs for health indicators
            logs = container.get_logs()
            health_indicators = [
                "Starting MCP server",
                "Server initialized",
                "FastMCP",
                "transport",
            ]

            found_indicators = [
                indicator for indicator in health_indicators if indicator in logs
            ]
            assert (
                len(found_indicators) > 0
            ), f"Container logs should contain health indicators. Logs: {logs}"

    def test_configuration_mapping(self, deployer):
        """Test configuration mapping works correctly."""
        if "github" not in deployer.templates:
            pytest.skip("github template not available")

        template = deployer.templates["github"]

        # Test file config mapping
        file_config = {
            "default_owner": "",
            "default_repo": "",
            "api_base_url": "https://api.github.com",
            "max_search_results": 30,
            "enable_webhook_events": False,
            "rate_limit_requests": 5000,
        }

        result = deployer._map_file_config_to_env(file_config, template)

        # Should produce environment variables
        assert (
            len(result) > 0
        ), "Configuration mapping should produce environment variables"

        # All values should be strings (for environment variables)
        for key, value in result.items():
            assert isinstance(
                value, str
            ), f"Environment variable {key} should be string, got {type(value)}"
