name: Template Tests

on:
  push:
    branches: [ main, develop, refactor ]
  pull_request:
    branches: [ main, develop ]

env:
  PYTHON_VERSION: '3.11'

jobs:
  test-templates:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: [demo]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Test template ${{ matrix.template }}
      run: |
        cd templates/${{ matrix.template }}
        python -m pytest tests/ -v

    - name: Test template creation
      run: |
        python -m pytest tests/test_template_creation.py -v
